import type { AlunoIdiomaResponse, CompetenciaResponse, ContatoResponse, ExperienciaResponse, ModalidadeTrabalho, ProjetoResponse, StatusFormacao, StatusValidacaoRpv, TipoDisponibilidade, TipoFormacao } from "@/types/student";

export interface PaginatedResponse<T> { items: T[]; page: number; pageSize: number; totalItems: number; totalPages: number; }
export interface AdminDashboard { alunosAtivos: number; recrutadoresAtivos: number; solicitacoesCadastroPendentes: number; validacoesRpvPendentes: number; perfisAtualizadosUltimos7Dias: number; formacoesRpvVerificadas: number; competenciasMaisUtilizadas: { id: number; nome: string; quantidadeAlunos: number }[]; }
export type RegistrationRequestType = "ALUNO" | "RECRUTADOR";
export type RegistrationRequestStatus = "PENDENTE" | "APROVADA" | "REJEITADA";
export interface AdminRegistrationRequest { id: string; tipo: RegistrationRequestType; status: RegistrationRequestStatus; nomeCompleto: string; email: string; telefone: string; cidade: string; uf: string; instituicaoEnsino: string | null; curso: string | null; tipoFormacao: TipoFormacao | null; anoConclusaoPrevisto: number | null; empresa: string | null; cargo: string | null; criadoEm: string; }
export interface AdminRegistrationRequestDetail extends AdminRegistrationRequest { relacaoRioPombaValley: string | null; siteEmpresa: string | null; analisadoEm: string | null; adminEmail: string | null; motivoRejeicao: string | null; }
export interface AdminStudentListItem { id: string; slug: string; nomeCompleto: string; fotoUrl: string | null; cidade: string | null; uf: string | null; ativo: boolean; atualizadoEm: string; }
export interface AdminFormation { id: string; tipo: TipoFormacao; nome: string; instituicao: string; dataInicio: string; dataFim: string | null; cargaHoraria: number | null; status: StatusFormacao; principal: boolean; ehRioPombaValley: boolean; statusValidacaoRpv: StatusValidacaoRpv | null; possuiCertificado: boolean; certificadoUrl: string | null; }
export interface AdminStudentDetail { id: string; slug: string; nomeCompleto: string; ativo: boolean; fotoUrl: string | null; cidade: string | null; uf: string | null; contato: ContatoResponse; bio: string | null; competencias: CompetenciaResponse[]; idiomas: AlunoIdiomaResponse[]; disponibilidades: TipoDisponibilidade[]; modalidades: ModalidadeTrabalho[]; formacoes: AdminFormation[]; experiencias: ExperienciaResponse[]; projetos: ProjetoResponse[]; curriculo: { possuiCurriculo: boolean; url: string | null }; atualizadoEm: string; }
export interface AdminRecruiter { id: string; nomeCompleto: string; empresa: string; cargo: string; cidade: string; uf: string; status: "ATIVO" | "BLOQUEADO"; ultimoAcessoEm: string | null; }
export interface AdminRecruiterDetail extends AdminRecruiter { email: string; telefone: string; }
export interface RpvValidation { formacaoId: string; alunoId: string; alunoNome: string; alunoSlug: string; alunoAtivo: boolean; tipo: TipoFormacao; nome: string; instituicao: string; dataInicio: string; dataFim: string | null; cargaHoraria: number | null; status: StatusFormacao; principal: boolean; possuiCertificado: boolean; atualizadoEm: string; }
export interface RpvValidationDetail { formacaoId: string; aluno: { id: string; nomeCompleto: string; slug: string; ativo: boolean; cidade: string | null; uf: string | null }; formacao: Omit<RpvValidation, "formacaoId" | "alunoId" | "alunoNome" | "alunoSlug" | "alunoAtivo"> & { ehRioPombaValley: boolean; statusValidacaoRpv: StatusValidacaoRpv }; }
export interface AuditItem { id: string; acao: string; adminEmail: string; entidadeTipo: string; entidadeId: string; descricao: string; criadoEm: string; }
