// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalentValley.Api.Data;

#nullable disable

namespace TalentValley.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911102241_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Aluno", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasMaxLength(1500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurriculoStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailProfissional")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("AtualizadoEm");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Uf", "Cidade");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.AlunoCompetencia", b =>
                {
                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunoId", "CompetenciaId");

                    b.HasIndex("CompetenciaId", "AlunoId");

                    b.ToTable("AlunoCompetencias");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.AlunoDisponibilidade", b =>
                {
                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoId", "Tipo");

                    b.HasIndex("Tipo", "AlunoId");

                    b.ToTable("AlunoDisponibilidades");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.AlunoIdioma", b =>
                {
                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdiomaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoId", "IdiomaId");

                    b.HasIndex("IdiomaId");

                    b.ToTable("AlunoIdiomas");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.AlunoModalidade", b =>
                {
                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modalidade")
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoId", "Modalidade");

                    b.HasIndex("Modalidade", "AlunoId");

                    b.ToTable("AlunoModalidades");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LoginAnteriorEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeBusca")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UltimoLoginEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NomeBusca");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminEmailSnapshot")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadeId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadeTipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Acao");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("CriadoEm");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Competencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeBusca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NomeBusca")
                        .IsUnique();

                    b.ToTable("Competencias");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Experiencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Atual")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Experiencias");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Favorito", b =>
                {
                    b.Property<Guid>("RecrutadorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("RecrutadorId", "AlunoId");

                    b.HasIndex("AlunoId");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Formacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificadoStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EhRioPombaValley")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeBusca")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Principal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusValidacaoRpv")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ValidadoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("AtualizadoEm");

                    b.HasIndex("NomeBusca");

                    b.HasIndex("EhRioPombaValley", "StatusValidacaoRpv");

                    b.HasIndex("Tipo", "Status");

                    b.HasIndex(new[] { "AlunoId" }, "IX_Formacoes_AlunoId_Principal")
                        .IsUnique()
                        .HasFilter("\"Principal\" = 1");

                    b.ToTable("Formacoes");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Idioma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeBusca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NomeBusca")
                        .IsUnique();

                    b.ToTable("Idiomas");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Projeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmAndamento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepositorioUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("AtualizadoEm");

                    b.HasIndex("AlunoId", "Ordem")
                        .IsUnique();

                    b.ToTable("Projetos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Projetos_Ordem", "\"Ordem\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.ProjetoCompetencia", b =>
                {
                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjetoId", "CompetenciaId");

                    b.HasIndex("CompetenciaId", "ProjetoId");

                    b.ToTable("ProjetoCompetencias");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Recrutador", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Status");

                    b.ToTable("Recrutadores");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TalentValley.Api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TalentValley.Api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentValley.Api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TalentValley.Api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("TalentValley.Api.Domain.Entities.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("TalentValley.Api.Domain.Entities.Aluno", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.AlunoCompetencia", b =>
                {
                    b.HasOne("TalentValley.Api.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Competencias")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentValley.Api.Domain.Entities.Competencia", "Competencia")
                        .WithMany("Alunos")
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Competencia");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.AlunoDisponibilidade", b =>
                {
                    b.HasOne("TalentValley.Api.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.AlunoIdioma", b =>
                {
                    b.HasOne("TalentValley.Api.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Idiomas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentValley.Api.Domain.Entities.Idioma", "Idioma")
                        .WithMany("Alunos")
                        .HasForeignKey("IdiomaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Idioma");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.AlunoModalidade", b =>
                {
                    b.HasOne("TalentValley.Api.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Modalidades")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("TalentValley.Api.Domain.Entities.ApplicationUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Experiencia", b =>
                {
                    b.HasOne("TalentValley.Api.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Experiencias")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Favorito", b =>
                {
                    b.HasOne("TalentValley.Api.Domain.Entities.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentValley.Api.Domain.Entities.Recrutador", "Recrutador")
                        .WithMany()
                        .HasForeignKey("RecrutadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Recrutador");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Formacao", b =>
                {
                    b.HasOne("TalentValley.Api.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Formacoes")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Projeto", b =>
                {
                    b.HasOne("TalentValley.Api.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Projetos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.ProjetoCompetencia", b =>
                {
                    b.HasOne("TalentValley.Api.Domain.Entities.Competencia", "Competencia")
                        .WithMany("Projetos")
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TalentValley.Api.Domain.Entities.Projeto", "Projeto")
                        .WithMany("Competencias")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competencia");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Recrutador", b =>
                {
                    b.HasOne("TalentValley.Api.Domain.Entities.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("TalentValley.Api.Domain.Entities.Recrutador", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("Competencias");

                    b.Navigation("Disponibilidades");

                    b.Navigation("Experiencias");

                    b.Navigation("Formacoes");

                    b.Navigation("Idiomas");

                    b.Navigation("Modalidades");

                    b.Navigation("Projetos");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Competencia", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Projetos");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Idioma", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("TalentValley.Api.Domain.Entities.Projeto", b =>
                {
                    b.Navigation("Competencias");
                });
#pragma warning restore 612, 618
        }
    }
}
