"use client";

import { useState, type FormEvent } from "react";
import Link from "next/link";
import { Alert, Box, Button, Container, MenuItem, Paper, Stack, TextField, Typography } from "@mui/material";
import { GuestOnly } from "@/components/auth/GuestOnly";
import { registrationApi } from "@/lib/admin";
import { getApiErrorMessage } from "@/lib/api";
import { TIPO_FORMACAO_LABELS } from "@/lib/labels";
import {
  BRAZILIAN_UFS, normalizeEmailInput, normalizePhone, normalizeWhitespace, sanitizeCityName,
  sanitizeIntegerInput, sanitizePersonName, stripEmoji, validateBrazilianPhone, validateCityName,
  validateCompanyName, validateCourseName, validateEmail, validateFreeText, validateHttpUrl,
  validateInstitutionName, validateJobTitle, validatePersonName, validateUF, validateYear,
} from "@/lib/validation";
import type { TipoFormacao } from "@/types/student";

type FieldErrors = Record<string, string | null>;
type CommonForm = { nomeCompleto: string; email: string; telefone: string; cidade: string; uf: string };

const formations = Object.keys(TIPO_FORMACAO_LABELS) as TipoFormacao[];
const commonBlank: CommonForm = { nomeCompleto: "", email: "", telefone: "", cidade: "", uf: "" };

function PublicPage({ title, children }: { title: string; children: React.ReactNode }) {
  return <GuestOnly><Box component="main" sx={{ minHeight: "100dvh", py: { xs: 4, md: 7 }, px: 2, bgcolor: "background.default" }}><Container maxWidth="sm"><Paper elevation={0} sx={{ p: { xs: 3, sm: 4 }, border: 1, borderColor: "divider" }}><Stack spacing={3}><Stack spacing={0.75}><Typography component="h1" variant="h4">{title}</Typography><Typography color="text.secondary">Seu pedido será analisado pela equipe do Talent Valley antes da criação da conta.</Typography></Stack>{children}</Stack></Paper></Container></Box></GuestOnly>;
}

function Success() { return <Alert severity="success"><Typography sx={{ fontWeight: 700 }}>Solicitação enviada com sucesso.</Typography><Typography variant="body2">Seu cadastro será analisado pela equipe do Talent Valley. Se aprovado, você receberá as instruções para ativar sua conta.</Typography></Alert>; }
function commonErrors(form: CommonForm): FieldErrors { return { nomeCompleto: validatePersonName(form.nomeCompleto), email: validateEmail(form.email), telefone: validateBrazilianPhone(form.telefone), cidade: validateCityName(form.cidade), uf: validateUF(form.uf) }; }
function firstError(errors: FieldErrors): string | null { return Object.values(errors).find((error): error is string => Boolean(error)) ?? null; }

function CommonFields({ value, errors, onChange, onBlur, disabled }: { value: CommonForm; errors: FieldErrors; onChange: (key: keyof CommonForm, value: string) => void; onBlur: (key: keyof CommonForm) => void; disabled: boolean }) {
  return <>
    <TextField required label="Nome completo" autoComplete="name" value={value.nomeCompleto} onChange={(e) => onChange("nomeCompleto", sanitizePersonName(e.target.value))} onBlur={() => onBlur("nomeCompleto")} disabled={disabled} error={Boolean(errors.nomeCompleto)} helperText={errors.nomeCompleto} slotProps={{ htmlInput: { maxLength: 150 } }} />
    <TextField required type="email" label="E-mail" autoComplete="email" value={value.email} onChange={(e) => onChange("email", e.target.value.slice(0, 254))} onBlur={() => onBlur("email")} disabled={disabled} error={Boolean(errors.email)} helperText={errors.email} slotProps={{ htmlInput: { maxLength: 254, autoCapitalize: "none" } }} />
    <TextField required type="tel" label="Telefone" value={value.telefone} onChange={(e) => onChange("telefone", e.target.value)} onBlur={() => onBlur("telefone")} disabled={disabled} error={Boolean(errors.telefone)} helperText={errors.telefone ?? "Ex.: (32) 99999-9999"} slotProps={{ htmlInput: { inputMode: "tel" } }} />
    <TextField required label="Cidade" value={value.cidade} onChange={(e) => onChange("cidade", sanitizeCityName(e.target.value))} onBlur={() => onBlur("cidade")} disabled={disabled} error={Boolean(errors.cidade)} helperText={errors.cidade} slotProps={{ htmlInput: { maxLength: 120 } }} />
    <TextField required select label="UF" value={value.uf} onChange={(e) => onChange("uf", e.target.value)} onBlur={() => onBlur("uf")} disabled={disabled} error={Boolean(errors.uf)} helperText={errors.uf}><MenuItem value="">Selecione</MenuItem>{BRAZILIAN_UFS.map((uf) => <MenuItem key={uf} value={uf}>{uf}</MenuItem>)}</TextField>
  </>;
}

export function RegistrationChoice() { return <PublicPage title="Solicitar acesso ao Talent Valley"><Stack spacing={1.5}><Paper component={Link} href="/cadastro/aluno" elevation={0} sx={{ p: 2.25, border: 1, borderColor: "divider", textDecoration: "none", color: "text.primary" }}><Typography sx={{ fontWeight: 700 }}>Sou aluno</Typography><Typography variant="body2" color="text.secondary">Envie seus dados para análise. Após aprovação, você receberá acesso para criar seu perfil profissional.</Typography></Paper><Paper component={Link} href="/cadastro/recrutador" elevation={0} sx={{ p: 2.25, border: 1, borderColor: "divider", textDecoration: "none", color: "text.primary" }}><Typography sx={{ fontWeight: 700 }}>Sou Recrutador</Typography><Typography variant="body2" color="text.secondary">Solicite acesso para pesquisar talentos da comunidade Rio Pomba Valley.</Typography></Paper><Typography align="center" variant="body2">Já possui acesso? <Link href="/login">Entrar</Link></Typography></Stack></PublicPage>; }

export function StudentRegistrationForm() {
  const [common, setCommon] = useState(commonBlank); const [school, setSchool] = useState({ instituicaoEnsino: "", curso: "", tipoFormacao: "" as TipoFormacao | "", anoConclusaoPrevisto: "", relacaoRioPombaValley: "" }); const [errors, setErrors] = useState<FieldErrors>({}); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState(false);
  const validate = () => ({ ...commonErrors(common), instituicaoEnsino: validateInstitutionName(school.instituicaoEnsino), curso: validateCourseName(school.curso), tipoFormacao: school.tipoFormacao ? null : "Selecione um tipo de formação válido.", anoConclusaoPrevisto: validateYear(school.anoConclusaoPrevisto), relacaoRioPombaValley: school.relacaoRioPombaValley ? validateFreeText(school.relacaoRioPombaValley, 500) : null });
  const blurCommon = (key: keyof CommonForm) => setErrors((current) => ({ ...current, [key]: commonErrors(common)[key] }));
  const submit = async (event: FormEvent) => { event.preventDefault(); const nextErrors = validate(); setErrors(nextErrors); const validation = firstError(nextErrors); if (validation) { setError(validation); return; } setBusy(true); setError(null); try { await registrationApi.student({ ...common, ...school, nomeCompleto: normalizeWhitespace(common.nomeCompleto), email: normalizeEmailInput(common.email), telefone: normalizePhone(common.telefone), cidade: normalizeWhitespace(common.cidade), uf: common.uf, instituicaoEnsino: normalizeWhitespace(school.instituicaoEnsino), curso: normalizeWhitespace(school.curso), tipoFormacao: school.tipoFormacao as TipoFormacao, anoConclusaoPrevisto: school.anoConclusaoPrevisto ? Number(school.anoConclusaoPrevisto) : null, relacaoRioPombaValley: school.relacaoRioPombaValley.trim() || null }); setSuccess(true); } catch (reason) { setError(getApiErrorMessage(reason, "Não foi possível enviar a solicitação.")); } finally { setBusy(false); } };
  return <PublicPage title="Solicitar acesso como aluno">{success ? <Success /> : <Box component="form" onSubmit={submit} noValidate><Stack spacing={2}>{error && <Alert severity="error">{error}</Alert>}<CommonFields value={common} errors={errors} onChange={(key, value) => { setCommon((current) => ({ ...current, [key]: value })); setErrors((current) => ({ ...current, [key]: null })); }} onBlur={blurCommon} disabled={busy} /><TextField required label="Instituição de ensino" value={school.instituicaoEnsino} onChange={(e) => setSchool((x) => ({ ...x, instituicaoEnsino: e.target.value.slice(0, 180) }))} onBlur={() => setErrors((x) => ({ ...x, instituicaoEnsino: validateInstitutionName(school.instituicaoEnsino) }))} disabled={busy} error={Boolean(errors.instituicaoEnsino)} helperText={errors.instituicaoEnsino} slotProps={{ htmlInput: { maxLength: 180 } }} /><TextField required label="Curso" value={school.curso} onChange={(e) => setSchool((x) => ({ ...x, curso: e.target.value.slice(0, 180) }))} onBlur={() => setErrors((x) => ({ ...x, curso: validateCourseName(school.curso) }))} disabled={busy} error={Boolean(errors.curso)} helperText={errors.curso} slotProps={{ htmlInput: { maxLength: 180 } }} /><TextField required select label="Tipo de formação" value={school.tipoFormacao} onChange={(e) => setSchool((x) => ({ ...x, tipoFormacao: e.target.value as TipoFormacao }))} disabled={busy} error={Boolean(errors.tipoFormacao)} helperText={errors.tipoFormacao}>{formations.map((type) => <MenuItem key={type} value={type}>{TIPO_FORMACAO_LABELS[type]}</MenuItem>)}</TextField><TextField label="Ano previsto de conclusão" value={school.anoConclusaoPrevisto} onChange={(e) => setSchool((x) => ({ ...x, anoConclusaoPrevisto: sanitizeIntegerInput(e.target.value, 4) }))} disabled={busy} error={Boolean(errors.anoConclusaoPrevisto)} helperText={errors.anoConclusaoPrevisto ?? "Opcional; use quatro dígitos."} slotProps={{ htmlInput: { inputMode: "numeric", pattern: "[0-9]*", maxLength: 4 } }} /><TextField multiline minRows={3} label="Relação com o Rio Pomba Valley (opcional)" value={school.relacaoRioPombaValley} onChange={(e) => setSchool((x) => ({ ...x, relacaoRioPombaValley: stripEmoji(e.target.value).slice(0, 500) }))} disabled={busy} error={Boolean(errors.relacaoRioPombaValley)} helperText={errors.relacaoRioPombaValley} slotProps={{ htmlInput: { maxLength: 500 } }} /><Button type="submit" variant="contained" size="large" disabled={busy}>{busy ? "Enviando..." : "Enviar solicitação"}</Button></Stack></Box>}</PublicPage>;
}

export function RecruiterRegistrationForm() {
  const [common, setCommon] = useState(commonBlank); const [extra, setExtra] = useState({ empresa: "", cargo: "", siteEmpresa: "" }); const [errors, setErrors] = useState<FieldErrors>({}); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState(false);
  const validate = () => ({ ...commonErrors(common), empresa: validateCompanyName(extra.empresa), cargo: validateJobTitle(extra.cargo), siteEmpresa: validateHttpUrl(extra.siteEmpresa) }); const blurCommon = (key: keyof CommonForm) => setErrors((current) => ({ ...current, [key]: commonErrors(common)[key] }));
  const submit = async (event: FormEvent) => { event.preventDefault(); const nextErrors = validate(); setErrors(nextErrors); const validation = firstError(nextErrors); if (validation) { setError(validation); return; } setBusy(true); setError(null); try { await registrationApi.recruiter({ ...common, ...extra, nomeCompleto: normalizeWhitespace(common.nomeCompleto), email: normalizeEmailInput(common.email), telefone: normalizePhone(common.telefone), cidade: normalizeWhitespace(common.cidade), uf: common.uf, empresa: normalizeWhitespace(extra.empresa), cargo: normalizeWhitespace(extra.cargo), siteEmpresa: extra.siteEmpresa.trim() || null }); setSuccess(true); } catch (reason) { setError(getApiErrorMessage(reason, "Não foi possível enviar a solicitação.")); } finally { setBusy(false); } };
  return <PublicPage title="Solicitar acesso como recrutador">{success ? <Success /> : <Box component="form" onSubmit={submit} noValidate><Stack spacing={2}>{error && <Alert severity="error">{error}</Alert>}<CommonFields value={common} errors={errors} onChange={(key, value) => { setCommon((current) => ({ ...current, [key]: value })); setErrors((current) => ({ ...current, [key]: null })); }} onBlur={blurCommon} disabled={busy} /><TextField required label="Empresa" value={extra.empresa} onChange={(e) => setExtra((x) => ({ ...x, empresa: e.target.value.slice(0, 150) }))} onBlur={() => setErrors((x) => ({ ...x, empresa: validateCompanyName(extra.empresa) }))} disabled={busy} error={Boolean(errors.empresa)} helperText={errors.empresa} slotProps={{ htmlInput: { maxLength: 150 } }} /><TextField required label="Cargo" value={extra.cargo} onChange={(e) => setExtra((x) => ({ ...x, cargo: e.target.value.slice(0, 120) }))} onBlur={() => setErrors((x) => ({ ...x, cargo: validateJobTitle(extra.cargo) }))} disabled={busy} error={Boolean(errors.cargo)} helperText={errors.cargo} slotProps={{ htmlInput: { maxLength: 120 } }} /><TextField type="url" label="Site da empresa (opcional)" value={extra.siteEmpresa} onChange={(e) => setExtra((x) => ({ ...x, siteEmpresa: e.target.value.slice(0, 2048) }))} onBlur={() => setErrors((x) => ({ ...x, siteEmpresa: validateHttpUrl(extra.siteEmpresa) }))} disabled={busy} error={Boolean(errors.siteEmpresa)} helperText={errors.siteEmpresa ?? "Use um endereço HTTP ou HTTPS."} slotProps={{ htmlInput: { maxLength: 2048, inputMode: "url" } }} /><Button type="submit" variant="contained" size="large" disabled={busy}>{busy ? "Enviando..." : "Enviar solicitação"}</Button></Stack></Box>}</PublicPage>;
}
