namespace TalentValley.Api.Domain.Enums;

public enum AcaoAuditoria
{
    ALUNO_CRIADO,
    ALUNO_BLOQUEADO,
    ALUNO_REATIVADO,
    ALUNO_EXCLUIDO,
    RECRUTADOR_CRIADO,
    RECRUTADOR_BLOQUEADO,
    RECRUTADOR_REATIVADO,
    RECRUTADOR_EXCLUIDO,
    SOLICITACAO_CADASTRO_APROVADA,
    SOLICITACAO_CADASTRO_REJEITADA,
    FORMACAO_RPV_APROVADA,
    FORMACAO_RPV_REJEITADA,
    FORMACAO_RPV_VALIDACAO_REMOVIDA
}
